-- MySQL Script generated by MySQL Workbench
-- Sat Jul 15 21:39:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_pedido
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_pedido
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_pedido` DEFAULT CHARACTER SET utf8 ;
USE `sistema_pedido` ;

-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_persona` (
  `identidad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`identidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_empleado` (
  `rtn` INT NOT NULL,
  `tbl_persona_identidad` INT NOT NULL,
  `cargo_asignado` VARCHAR(45) NULL,
  `fecha_contratacion` VARCHAR(45) NULL,
  PRIMARY KEY (`rtn`, `tbl_persona_identidad`),
  INDEX `fk_tbl_empleado_tbl_persona_idx` (`tbl_persona_identidad` ASC),
  CONSTRAINT `fk_tbl_empleado_tbl_persona`
    FOREIGN KEY (`tbl_persona_identidad`)
    REFERENCES `sistema_pedido`.`tbl_persona` (`identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_usuario` (
  `id` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `contrasenia_usuario` VARCHAR(45) NULL,
  `tbl_empleado_rtn` INT NOT NULL,
  `tbl_empleado_tbl_persona_identidad` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_empleado_rtn`, `tbl_empleado_tbl_persona_identidad`),
  INDEX `fk_tbl_usuario_tbl_empleado1_idx` (`tbl_empleado_rtn` ASC, `tbl_empleado_tbl_persona_identidad` ASC),
  CONSTRAINT `fk_tbl_usuario_tbl_empleado1`
    FOREIGN KEY (`tbl_empleado_rtn` , `tbl_empleado_tbl_persona_identidad`)
    REFERENCES `sistema_pedido`.`tbl_empleado` (`rtn` , `tbl_persona_identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_empresa` (
  `rtn` INT NOT NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `nombre_corto` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `web` VARCHAR(45) NULL,
  PRIMARY KEY (`rtn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_articulo` (
  `referencia` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  PRIMARY KEY (`referencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_cliente` (
  `rtn` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `tbl_persona_identidad` INT NOT NULL,
  PRIMARY KEY (`rtn`, `tbl_persona_identidad`),
  INDEX `fk_tbl_cliente_tbl_persona1_idx` (`tbl_persona_identidad` ASC),
  CONSTRAINT `fk_tbl_cliente_tbl_persona1`
    FOREIGN KEY (`tbl_persona_identidad`)
    REFERENCES `sistema_pedido`.`tbl_persona` (`identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_estado` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_pedido` (
  `id` INT NOT NULL,
  `fecha_entrega` DATE NULL,
  `fecha_solicitud` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `total_pedido` VARCHAR(45) NULL,
  `tbl_cliente_rtn` INT NOT NULL,
  `tbl_cliente_tbl_persona_identidad` INT NOT NULL,
  `tbl_usuario_id` INT NOT NULL,
  `tbl_usuario_tbl_empleado_rtn` INT NOT NULL,
  `tbl_usuario_tbl_empleado_tbl_persona_identidad` INT NOT NULL,
  `tbl_estado_pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_cliente_rtn`, `tbl_cliente_tbl_persona_identidad`, `tbl_usuario_id`, `tbl_usuario_tbl_empleado_rtn`, `tbl_usuario_tbl_empleado_tbl_persona_identidad`, `tbl_estado_pedido_id`),
  INDEX `fk_tbl_pedido_tbl_cliente1_idx` (`tbl_cliente_rtn` ASC, `tbl_cliente_tbl_persona_identidad` ASC),
  INDEX `fk_tbl_pedido_tbl_usuario1_idx` (`tbl_usuario_id` ASC, `tbl_usuario_tbl_empleado_rtn` ASC, `tbl_usuario_tbl_empleado_tbl_persona_identidad` ASC),
  INDEX `fk_tbl_pedido_tbl_estado_pedido1_idx` (`tbl_estado_pedido_id` ASC),
  CONSTRAINT `fk_tbl_pedido_tbl_cliente1`
    FOREIGN KEY (`tbl_cliente_rtn` , `tbl_cliente_tbl_persona_identidad`)
    REFERENCES `sistema_pedido`.`tbl_cliente` (`rtn` , `tbl_persona_identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_id` , `tbl_usuario_tbl_empleado_rtn` , `tbl_usuario_tbl_empleado_tbl_persona_identidad`)
    REFERENCES `sistema_pedido`.`tbl_usuario` (`id` , `tbl_empleado_rtn` , `tbl_empleado_tbl_persona_identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_estado_pedido1`
    FOREIGN KEY (`tbl_estado_pedido_id`)
    REFERENCES `sistema_pedido`.`tbl_estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_pedido_has_tbl_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_pedido_has_tbl_articulo` (
  `tbl_pedido_id` INT NOT NULL,
  `tbl_articulo_referencia` INT NOT NULL,
  `tbl_estado_pedido_id` INT NOT NULL,
  PRIMARY KEY (`tbl_pedido_id`, `tbl_articulo_referencia`, `tbl_estado_pedido_id`),
  INDEX `fk_tbl_pedido_has_tbl_articulo_tbl_articulo1_idx` (`tbl_articulo_referencia` ASC),
  INDEX `fk_tbl_pedido_has_tbl_articulo_tbl_pedido1_idx` (`tbl_pedido_id` ASC),
  INDEX `fk_tbl_pedido_has_tbl_articulo_tbl_estado_pedido1_idx` (`tbl_estado_pedido_id` ASC),
  CONSTRAINT `fk_tbl_pedido_has_tbl_articulo_tbl_pedido1`
    FOREIGN KEY (`tbl_pedido_id`)
    REFERENCES `sistema_pedido`.`tbl_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_has_tbl_articulo_tbl_articulo1`
    FOREIGN KEY (`tbl_articulo_referencia`)
    REFERENCES `sistema_pedido`.`tbl_articulo` (`referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_has_tbl_articulo_tbl_estado_pedido1`
    FOREIGN KEY (`tbl_estado_pedido_id`)
    REFERENCES `sistema_pedido`.`tbl_estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pedido`.`tbl_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pedido`.`tbl_historial` (
  `id` INT NOT NULL,
  `tipo_accion` VARCHAR(45) NULL,
  `detalle_accion` VARCHAR(45) NULL,
  `tbl_usuario_id` INT NOT NULL,
  `tbl_usuario_tbl_empleado_rtn` INT NOT NULL,
  `tbl_usuario_tbl_empleado_tbl_persona_identidad` INT NOT NULL,
  `ip` VARCHAR(45) NULL,
  `fecha_accion` DATETIME NULL,
  PRIMARY KEY (`id`, `tbl_usuario_id`, `tbl_usuario_tbl_empleado_rtn`, `tbl_usuario_tbl_empleado_tbl_persona_identidad`),
  INDEX `fk_tbl_historial_tbl_usuario1_idx` (`tbl_usuario_id` ASC, `tbl_usuario_tbl_empleado_rtn` ASC, `tbl_usuario_tbl_empleado_tbl_persona_identidad` ASC),
  CONSTRAINT `fk_tbl_historial_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_id` , `tbl_usuario_tbl_empleado_rtn` , `tbl_usuario_tbl_empleado_tbl_persona_identidad`)
    REFERENCES `sistema_pedido`.`tbl_usuario` (`id` , `tbl_empleado_rtn` , `tbl_empleado_tbl_persona_identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
